name: Run Selenium Tests

on:
  push:
    branches:
      - main  # Specify the branch to trigger the workflow (main in this case)
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # Specifies the OS where the job runs

    steps:
      - uses: actions/checkout@v2  # Step to checkout the repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Python version to be used

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install the required packages

      - name: Run Tests
        run: pytest  # Command to run the test suite
